### ISSUE TITLE
Missing command line build

### ISSUE THREAD

**Issue by DuncanL** [setsumi/Capture2Text#2]
I use the commandline version of the original;  but would like to take advantage of your updates to tesseract etc.
Will you be adding the CLI build back in?

**Comment by setsumi** [comment]
~~Well, I don't use CLI at all, this repo is just a fork of another person's project and I'm not familiar with the tools used, thus I don't have energy to research and implement it from the ground up. If someone is willing to do it PR is welcome of course.~~

**Comment by setsumi** [comment]
Oh, don't mind the above, I've completely forgot original already had CLI. So this is test build, could you test if it really works?
[Capture2Text_CLI.zip](https://github.com/user-attachments/files/16200643/Capture2Text_CLI.zip) (updated v2)

**Comment by DuncanL** [comment]
>  So this is test build, could you test if it really works? [Capture2Text_CLI.zip](https://github.com/user-attachments/files/16200643/Capture2Text_CLI.zip) (updated v2)

Yes - that seems to work perfectly.  Thank you!

In very unscientific side by side comparison;  it seems to be generally a little faster; but occasionally slower than the original.  No idea what's going on there;  but I'll take the improvements in the underlying engine anyway!

**Comment by setsumi** [comment]
Added CLI version to proper release.
